### ISSUE TITLE
[BUG] SPANISH LANG BROKEN

### ISSUE THREAD

**Issue by SrRapero720** [Ghost-chu/QuickShop-Reremake#1533]
### Description

I update to 5.0.0.0. i restart my server and now all signs change languaje to english. (before use spanish like default)
Also i put spanish manually but traslations are broken(? some traslasted words now are in english

EXAMPLE:
![image](https://user-images.githubusercontent.com/29090346/139576216-c133168b-9e6b-463e-916b-77d71ec2f692.png)
Title now say "adminshop" instead "tienda admin" and price is "[price] each" instead "[price] la unidad"

### Steps to reproduce

Update
Use default settings
BUG!

### Expected Behaviour

1. Use spanish like default (like before)
2. Use before traslated words

### Screenshots

COMPARATION (BEFORE-AFTER)
![image](https://user-images.githubusercontent.com/29090346/139576216-c133168b-9e6b-463e-916b-77d71ec2f692.png)
![2021-10-31_03h25_30](https://user-images.githubusercontent.com/29090346/139576364-69588a51-290f-42d0-9416-135301d49493.jpg)

### `/qs paste` URL

https://paste.helpch.at/reyutuhuvi

**Comment by Ghost-chu** [comment]
Please rejoin the server, and capture a screenshot that QuickShop locale detecting message that was sent to you.

**Comment by Ghost-chu** [comment]
also if you're on 5.0.0.0, please update to 5.0.0.1

**Comment by Zixasis** [comment]
![image](https://user-images.githubusercontent.com/29090346/139576610-b2c0ac83-8cd8-4945-825b-9d646e19ee71.png)

**Comment by Ghost-chu** [comment]
thanks for reporting, es_mx not exists on our crowdin translation platform, will add it later.

**Comment by Ghost-chu** [comment]
language mapping updated, will update in 3 hours

**Comment by Zixasis** [comment]
5.0.0.1 is reading bucle and start to use ALL RAM
![image](https://user-images.githubusercontent.com/29090346/139576702-0db44254-bac9-4985-8a58-71b1e12a8f58.png
![2021-10-31_03h50_19](https://user-images.githubusercontent.com/29090346/139576839-599da2a9-aae6-475a-ac99-11214bc3ba25.jpg)
)

**Comment by Ghost-chu** [comment]
in newer QuickShop version, we use language that following the client settings.

try to switch your client language option to `Español （España）` and check it again

**Comment by SrRapero720** [comment]
actually the plugin make the server never start... im going to rollback the plugin version...

**Comment by Ghost-chu** [comment]
> actually the plugin make the server never start... im going to rollback the plugin version...

probably downloading the translation, open dev-mode to check debug output

**Comment by SrRapero720** [comment]
Also i "find" the server starting bucle bug, in the settings the config.yml the CYN; symbol get broken and spam too many random symbol (first start update). And every server start the "random symbols" increased
![2021-10-31_04h13_14](https://user-images.githubusercontent.com/29090346/139577808-b5e1b2be-bf9e-48b5-87b8-abdc7cc8e340.jpg)
![2021-10-31_04h11_22](https://user-images.githubusercontent.com/29090346/139577857-fea63b12-2d66-4bfa-9b9e-01e2d85211a6.jpg)


When i delete that the server start normally.
![2021-10-31_04h09_24](https://user-images.githubusercontent.com/29090346/139577627-242aba46-2cb3-4991-8fb0-9c8607576460.jpg)
s
![2021-10-31_04h09_04](https://user-images.githubusercontent.com/29090346/139577630-80a47e5f-82b8-4d17-9b75-46a5379f8973.jpg)

But Isnt working.
![2021-10-31_04h05_03](https://user-images.githubusercontent.com/29090346/139577475-e9b6c104-7a0c-4605-80eb-047a6fd19fa1.jpg)

**Comment by Ghost-chu** [comment]
snapshot building

**Comment by Ghost-chu** [comment]
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/1894/
Download `QuickShop.jar`

Fixed the sign and locale fallback issue.


Follow the steps and try again:
0. Download the jar that mentioned above
1. find `language` in `config.yml`, set to `es-ES`, if it already does not exist, you can add it by yourself
2. start the server again
3. it should works now

**Comment by SrRapero720** [comment]
still not working
![image](https://user-images.githubusercontent.com/29090346/139579546-844d6806-097c-452d-aa83-9c9d7773c0da.png)
![image](https://user-images.githubusercontent.com/29090346/139579554-6584aa12-0c27-4159-9796-4255ea78ca9a.png)

**Comment by SrRapero720** [comment]
Also the en_us JSON lang is spanish_english fusion. and all translation json files are empty
![2021-10-31_05h05_20](https://user-images.githubusercontent.com/29090346/139579835-331d5558-222d-4b49-ad9c-d7b021f5299e.jpg)
![image](https://user-images.githubusercontent.com/29090346/139579900-30ad6a73-6e96-46fb-aa47-fdeb7b37be36.png)

**Comment by SrRapero720** [comment]
I delete all config folder and regen and now work...
![2021-10-31_05h14_41](https://user-images.githubusercontent.com/29090346/139580291-0f79158b-5c69-4b7d-a985-2d8ae39ae008.jpg)

**Comment by Ghost-chu** [comment]
Move to https://github.com/Ghost-chu/QuickShop-Reremake/issues/1537
