### ISSUE TITLE
[BUG]Nothing in it when buying a shulker box with something in

### ISSUE THREAD

**Issue by dixiatielu** [Ghost-chu/QuickShop-Reremake#420]
**Describe the bug**
The preview of the items in the chest can get the customers interested of the shulker box, but they 
will find nothing in the box if someone reproduce the bug

**To Reproduce**
1. Create a shop and sell a shulker box with something in it
2. Get another another empty shulker box and put it into the chest shop
3. Someone can buy it with the preview of many things in the box
4. See error: nothing is in the box.

**Expected behavior**
The shop owner should be stoppen when trying to put an empty shulker box to the shop of shulker boxes with things in it.

**Screenshots**
Here is a player's screen record
![QQ图片20200417204855](https://user-images.githubusercontent.com/29675002/79570982-f63c3700-80ec-11ea-927c-998a6ea0c0a6.png)
![QQ图片20200417204900](https://user-images.githubusercontent.com/29675002/79570986-f76d6400-80ec-11ea-81b1-c7b1eda1836a.png)

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- https://paste.enginehub.org/ollLgw-sN

**Additional context**

**Comment by Ghost-chu** [comment]
It seems is same issue -> https://github.com/Ghost-chu/QuickShop-Reremake/issues/394

**Comment by sandtechnology** [comment]
It should be a server bug, you should update you server jar

**Comment by Ghost-chu** [comment]
> It should be a server bug, you should update your server jar

That not a server bug.

**Comment by sandtechnology** [comment]
> 
> 
> > It should be a server bug, you should update your server jar
> 
> That not a server bug.
> 
> ```
> Create a shop and sell a shulker box with something in it
> Get another another empty shulker box and put it into the chest shop
> ```

nvm just fixed in the latest verison

**Comment by dixiatielu** [comment]
> > > It should be a server bug, you should update your server jar
> > 
> > 
> > That not a server bug.
> > ```
> > Create a shop and sell a shulker box with something in it
> > Get another another empty shulker box and put it into the chest shop
> > ```
> 
> nvm just fixed in the latest verison

Sorry, but I'm sure I'm using the latest version of paper for Minecraft 1.15.2 and the latest version 3.1.4.32, but the bug still exists after serveral times of trying.

**Comment by sandtechnology** [comment]
> 
> 
> > > > It should be a server bug, you should update your server jar
> > > 
> > > 
> > > That not a server bug.
> > > ```
> > > Create a shop and sell a shulker box with something in it
> > > Get another another empty shulker box and put it into the chest shop
> > > ```
> > 
> > 
> > nvm just fixed in the latest verison
> 
> Sorry, but I'm sure I'm using the latest version of paper for Minecraft 1.15.2 and the latest version 3.1.4.32, but the bug still exists after serveral times of trying.

Is the bug still persist when you set work-type to 1 in config.yml?

**Comment by dixiatielu** [comment]
> > > > > It should be a server bug, you should update your server jar
> > > > 
> > > > 
> > > > That not a server bug.
> > > > ```
> > > > Create a shop and sell a shulker box with something in it
> > > > Get another another empty shulker box and put it into the chest shop
> > > > ```
> > > 
> > > 
> > > nvm just fixed in the latest verison
> > 
> > 
> > Sorry, but I'm sure I'm using the latest version of paper for Minecraft 1.15.2 and the latest version 3.1.4.32, but the bug still exists after serveral times of trying.
> 
> Is the bug still persist when you set work-type to 1 in config.yml?

Ohh, I've found it has been fixed... I thought the plugin will prevent the shop owner to put other things into the chest so I didn't realize the selling amount has been cleared to '0'. Sorry for botherring and thanks for promit reply. I'll also be careful before putting other issues later.
